export const skills: Record<string, string[]> = {
  "Languages & Frameworks": [
    "Go",
    "Python",
    "TypeScript",
    "JavaScript",
    "C#",
    "React",
    ".NET",
    "FastAPI",
    "Flask",
  ],
  "AI & Machine Learning": [
    "PyTorch",
    "TensorFlow",
    "LLMs",
    "RAG",
    "Transformers",
    "Scikit-learn",
    "MLOps",
  ],
  "Databases & Analytics": [
    "PostgreSQL",
    "MySQL",
    "Elasticsearch",
    "Databricks",
    "LanceDB",
    "NeptuneDB",
    "Redis",
    "Kafka",
  ],
  Practices: [
    "RESTful APIs",
    "Microservices",
    "CI/CD",
    "ETL",
    "Apache Spark",
    "Data Pipelines",
    "Model Evaluation",
  ],
};
